<?php

namespace app\modules\api;

/**
 * api module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'app\modules\api\controllers';

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \Yii\web\Response:: FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
